spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///D:/Projects/udemy-java-workspace/spring-cloud-microservices-udemy/git-localconfig-repo

server:
  port: 8888